server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
  elasticsearch:
    rest:
      uris: http://192.168.227.128:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.227.128
    port: 5672
    virtual-host: /ymx
    username: ymx
    password: ymx
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true

