server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.227.128:3306/guli_cart
    username: root
    password: 123456Abc@
  redis:
    port: 6379
    host: 192.168.227.128
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.227.128
    virtual-host: /ymx
    username: ymx
    password: ymx
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual

feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/cart/**/*.xml
  type-aliases-package: com.atguigu.gmall.cart.entity
  global-config:
    db-config:
      id-type: auto

jwt:
  pubKeyPath: E:\guli-gmall\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 8640000

