server:
  port: 18085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.227.128:3306/guli_oms
    username: root
    password: 123456Abc@
  redis:
    port: 6379
    host: 192.168.227.128
  rabbitmq:
    host: 192.168.227.128
    virtual-host: /ymx
    username: ymx
    password: ymx
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.atguigu.gmall: debug
