server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8791
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.227.128
feign:
  sentinel:
    enabled: true
thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepAlive: 60
    blockingQueueSize: 2000

